/* automatically generated by rust-bindgen 0.73.2 */

pub type __s8 = crate::ctypes::c_schar;
pub type __u8 = crate::ctypes::c_uchar;
pub type __s16 = crate::ctypes::c_short;
pub type __u16 = crate::ctypes::c_ushort;
pub type __s32 = crate::ctypes::c_int;
pub type __u32 = crate::ctypes::c_uint;
pub type __s64 = crate::ctypes::c_longlong;
pub type __u64 = crate::ctypes::c_ulonglong;
pub type __kernel_key_t = crate::ctypes::c_int;
pub type __kernel_mqd_t = crate::ctypes::c_int;
pub type __kernel_long_t = crate::ctypes::c_long;
pub type __kernel_ulong_t = crate::ctypes::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = crate::ctypes::c_uint;
pub type __kernel_pid_t = crate::ctypes::c_int;
pub type __kernel_ipc_pid_t = crate::ctypes::c_int;
pub type __kernel_uid_t = crate::ctypes::c_uint;
pub type __kernel_gid_t = crate::ctypes::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = crate::ctypes::c_int;
pub type __kernel_uid32_t = crate::ctypes::c_uint;
pub type __kernel_gid32_t = crate::ctypes::c_uint;
pub type __kernel_old_uid_t = __kernel_uid_t;
pub type __kernel_old_gid_t = __kernel_gid_t;
pub type __kernel_old_dev_t = crate::ctypes::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = crate::ctypes::c_longlong;
pub type __kernel_uoff_t = crate::ctypes::c_ulonglong;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = crate::ctypes::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = crate::ctypes::c_int;
pub type __kernel_clockid_t = crate::ctypes::c_int;
pub type __kernel_caddr_t = *mut crate::ctypes::c_char;
pub type __kernel_uid16_t = crate::ctypes::c_ushort;
pub type __kernel_gid16_t = crate::ctypes::c_ushort;
pub type __s128 = i128;
pub type __u128 = u128;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = crate::ctypes::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct keyctl_dh_params {
pub __bindgen_anon_1: keyctl_dh_params__bindgen_ty_1,
pub prime: __s32,
pub base: __s32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct keyctl_kdf_params {
pub hashname: *mut crate::ctypes::c_char,
pub otherinfo: *mut crate::ctypes::c_char,
pub otherinfolen: __u32,
pub __spare: [__u32; 8usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct keyctl_pkey_query {
pub supported_ops: __u32,
pub key_size: __u32,
pub max_data_size: __u16,
pub max_sig_size: __u16,
pub max_enc_size: __u16,
pub max_dec_size: __u16,
pub __spare: [__u32; 10usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct keyctl_pkey_params {
pub key_id: __s32,
pub in_len: __u32,
pub __bindgen_anon_1: keyctl_pkey_params__bindgen_ty_1,
pub __spare: [__u32; 7usize],
}
pub const __BITS_PER_LONG_LONG: u32 = 64;
pub const KEY_SPEC_THREAD_KEYRING: i32 = -1;
pub const KEY_SPEC_PROCESS_KEYRING: i32 = -2;
pub const KEY_SPEC_SESSION_KEYRING: i32 = -3;
pub const KEY_SPEC_USER_KEYRING: i32 = -4;
pub const KEY_SPEC_USER_SESSION_KEYRING: i32 = -5;
pub const KEY_SPEC_GROUP_KEYRING: i32 = -6;
pub const KEY_SPEC_REQKEY_AUTH_KEY: i32 = -7;
pub const KEY_SPEC_REQUESTOR_KEYRING: i32 = -8;
pub const KEY_REQKEY_DEFL_NO_CHANGE: i32 = -1;
pub const KEY_REQKEY_DEFL_DEFAULT: u32 = 0;
pub const KEY_REQKEY_DEFL_THREAD_KEYRING: u32 = 1;
pub const KEY_REQKEY_DEFL_PROCESS_KEYRING: u32 = 2;
pub const KEY_REQKEY_DEFL_SESSION_KEYRING: u32 = 3;
pub const KEY_REQKEY_DEFL_USER_KEYRING: u32 = 4;
pub const KEY_REQKEY_DEFL_USER_SESSION_KEYRING: u32 = 5;
pub const KEY_REQKEY_DEFL_GROUP_KEYRING: u32 = 6;
pub const KEY_REQKEY_DEFL_REQUESTOR_KEYRING: u32 = 7;
pub const KEYCTL_GET_KEYRING_ID: u32 = 0;
pub const KEYCTL_JOIN_SESSION_KEYRING: u32 = 1;
pub const KEYCTL_UPDATE: u32 = 2;
pub const KEYCTL_REVOKE: u32 = 3;
pub const KEYCTL_CHOWN: u32 = 4;
pub const KEYCTL_SETPERM: u32 = 5;
pub const KEYCTL_DESCRIBE: u32 = 6;
pub const KEYCTL_CLEAR: u32 = 7;
pub const KEYCTL_LINK: u32 = 8;
pub const KEYCTL_UNLINK: u32 = 9;
pub const KEYCTL_SEARCH: u32 = 10;
pub const KEYCTL_READ: u32 = 11;
pub const KEYCTL_INSTANTIATE: u32 = 12;
pub const KEYCTL_NEGATE: u32 = 13;
pub const KEYCTL_SET_REQKEY_KEYRING: u32 = 14;
pub const KEYCTL_SET_TIMEOUT: u32 = 15;
pub const KEYCTL_ASSUME_AUTHORITY: u32 = 16;
pub const KEYCTL_GET_SECURITY: u32 = 17;
pub const KEYCTL_SESSION_TO_PARENT: u32 = 18;
pub const KEYCTL_REJECT: u32 = 19;
pub const KEYCTL_INSTANTIATE_IOV: u32 = 20;
pub const KEYCTL_INVALIDATE: u32 = 21;
pub const KEYCTL_GET_PERSISTENT: u32 = 22;
pub const KEYCTL_DH_COMPUTE: u32 = 23;
pub const KEYCTL_PKEY_QUERY: u32 = 24;
pub const KEYCTL_PKEY_ENCRYPT: u32 = 25;
pub const KEYCTL_PKEY_DECRYPT: u32 = 26;
pub const KEYCTL_PKEY_SIGN: u32 = 27;
pub const KEYCTL_PKEY_VERIFY: u32 = 28;
pub const KEYCTL_RESTRICT_KEYRING: u32 = 29;
pub const KEYCTL_MOVE: u32 = 30;
pub const KEYCTL_CAPABILITIES: u32 = 31;
pub const KEYCTL_WATCH_KEY: u32 = 32;
pub const KEYCTL_SUPPORTS_ENCRYPT: u32 = 1;
pub const KEYCTL_SUPPORTS_DECRYPT: u32 = 2;
pub const KEYCTL_SUPPORTS_SIGN: u32 = 4;
pub const KEYCTL_SUPPORTS_VERIFY: u32 = 8;
pub const KEYCTL_MOVE_EXCL: u32 = 1;
pub const KEYCTL_CAPS0_CAPABILITIES: u32 = 1;
pub const KEYCTL_CAPS0_PERSISTENT_KEYRINGS: u32 = 2;
pub const KEYCTL_CAPS0_DIFFIE_HELLMAN: u32 = 4;
pub const KEYCTL_CAPS0_PUBLIC_KEY: u32 = 8;
pub const KEYCTL_CAPS0_BIG_KEY: u32 = 16;
pub const KEYCTL_CAPS0_INVALIDATE: u32 = 32;
pub const KEYCTL_CAPS0_RESTRICT_KEYRING: u32 = 64;
pub const KEYCTL_CAPS0_MOVE: u32 = 128;
pub const KEYCTL_CAPS1_NS_KEYRING_NAME: u32 = 1;
pub const KEYCTL_CAPS1_NS_KEY_TAG: u32 = 2;
pub const KEYCTL_CAPS1_NOTIFICATIONS: u32 = 4;
#[repr(C)]
#[derive(Copy, Clone)]
pub union keyctl_dh_params__bindgen_ty_1 {
pub private: __s32,
pub priv_: __s32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union keyctl_pkey_params__bindgen_ty_1 {
pub out_len: __u32,
pub in2_len: __u32,
}
